package Analizador;
import static Analizador.Tokens.*;

/* Sección de declaraciones de JFlex */
%%
%class Alexico
%type Tokens

/* Inicio de Expresiones regulares */
L=[a-zA-Z_]+
D=[0-9]+

Digito = [0-9]
Numero = {Digito} {Digito}*
Letra = [A-Za-z]
Palabra = {Letra} {Letra}*
Guion = "_"
Espacio=[ ,\t,\r,\n]+
Operador = "+"|"-"|"*"|"/"|"%"|"<"|"<="|">"|">="|"="|"=="|"!="|"&&"|"||"
Puntuacion = "!"|";"|","|"."
SignosA = "[]"|"()"|"{}"
Simbolos = "@"|"#"|"##"
SignosApertura = "["|"{"|"("
SignosCierre = "]"|"}"|")"

/* Finaliza expresiones regulares */

%{
    public String lexeme;
%}
%%
/* Finaliza la sección de declaraciones de JFlex */

/* Inicia sección de reglas */

/*PALABRAS RESERVADAS*/
ADD|EXTERNAL|PROCEDURE|ALL|FETCH|PUBLIC|ALTER|FILE|RAISERROR|AND|FILLFACTOR|READ|ANY|FOR|READTEXT|AS|FOREIGN|RECONFIGURE|
ASC|FREETEXT|REFERENCES|AUTHORIZATION|FREETEXTTABLE|REPLICATION|BACKUP|FROM|RESTORE|BEGIN|FULL|RESTRICT|BETWEEN|FUNCTION|
RETURN|BREAK|GOTO|REVERT|BROWSE|GRANT|REVOKE|BULK|GROUP|RIGHT|BY|HAVING|ROLLBACK|CASCADE|HOLDLOCK|ROWCOUNT|CASE|IDENTITY|
ROWGUIDCOL|CHECK|IDENTITY_INSERT|RULE|CHECKPOINT|IDENTITYCOL|SAVE|CLOSE|IF|SCHEMA|CLUSTERED|IN|SECURITYAUDIT|COALESCE|INDEX|
SELECT|COLLATE|INNER|SEMANTICKEYPHRASETABLE|COLUMN|INSERT|SEMANTICSIMILARITYDETAILSTABLE|COMMIT|INTERSECT|SEMANTICSIMILARITYTABLE|
COMPUTE|INTO|SESSION_USER|CONSTRAINT|IS|SET|CONTAINS|JOIN|SETUSER|CONTAINSTABLE|KEY|SHUTDOWN|CONTINUE|KILL|SOME|CONVERT|LEFT|
STATISTICS|CREATE|LIKE|SYSTEM_USER|CROSS|LINENO|TABLE|CURRENT|LOAD|TABLESAMPLE|CURRENT_DATE|MERGE|TEXTSIZE|CURRENT_TIME|NATIONAL|
THEN|CURRENT_TIMESTAMP|NOCHECK|TO|CURRENT_USER|NONCLUSTERED|TOP|CURSOR|NOT|TRAN|DATABASE|NULL|TRANSACTION|DBCC|NULLIF|TRIGGER|
DEALLOCATE|OF|TRUNCATE|DECLARE|OFF|TRY_CONVERT|DEFAULT|OFFSETS|TSEQUAL|DELETE|ON|UNION|DENY|OPEN|UNIQUE|DESC|OPENDATASOURCE|
UNPIVOT|DISK|OPENQUERY|UPDATE|DISTINCT|OPENROWSET|UPDATETEXT|DISTRIBUTED|OPENXML|USE|DOUBLE|OPTION|USER|DROP|OR|VALUES|DUMP|
ORDER|VARYING|ELSE|OUTER|VIEW|END|OVER|WAITFOR|ERRLVL|PERCENT|WHEN|ESCAPE|PIVOT|WHERE|EXCEPT|PLAN|WHILE|EXEC|PRECISION|WITH|
EXECUTE|PRIMARY|WITHIN GROUP|EXISTS|PRINT|WRITETEXT|EXIT|PROC|ABSOLUTE|OVERLAPS|ACTION|PAD|ADA|PARTIAL|PASCAL|EXTRACT|POSITION|
ALLOCATE|FALSE|PREPARE|FIRST|PRESERVE|FLOAT|ARE|PRIOR|PRIVILEGES|FORTRAN|ASSERTION|FOUND|AT|REAL|AVG|GET|GLOBAL|RELATIVE|GO|BIT|
BIT_LENGTH|BOTH|ROWS|HOUR|CASCADED|SCROLL|IMMEDIATE|SECOND|CAST|SECTION|CATALOG|INCLUDE|CHAR|SESSION|CHAR_LENGTH|INDICATOR|
CHARACTER|INITIALLY|CHARACTER_LENGTH|SIZE|INPUT|SMALLINT|INSENSITIVE|SPACE|INT|SQL|COLLATION|INTEGER|SQLCA|SQLCODE|INTERVAL|
SQLERROR|CONNECT|SQLSTATE|CONNECTION|SQLWARNING|ISOLATION|SUBSTRING|CONSTRAINTS|SUM|LANGUAGE|CORRESPONDING|LAST|TEMPORARY|COUNT|
LEADING|TIME|CROSS|LEVEL|TIMESTAMP|TIMEZONE_HOUR|LOCAL|TIMEZONE_MINUTE|LOWER|MATCH|TRAILING|MAX|MIN|TRANSLATE|DATE|MINUTE|
TRANSLATION|DAY|MODULE|TRIM|MONTH|TRUE|DEC|NAMES|DECIMAL|NATURAL|UNKNOWN|NCHAR|DEFERRABLE|NEXT|UPPER|DEFERRED|NO|USAGE|NONE|USING|
DESCRIBE|VALUE|DESCRIPTOR|DIAGNOSTICS|NUMERIC|VARCHAR|DISCONNECT|OCTET_LENGTH|DOMAIN|ONLY|WHENEVER|WORK|END-EXEC|WRITE|YEAR|
OUTPUT|ZONE|EXCEPTION {lexeme=yytext(); return Reservadas;}

/*ESPACIOS*/
{Espacio} {/*Ignore*/}

/*COMENTARIOS*/
"//".* {lexeme=yytext(); return Comentario;}
("/*".*"*/") {lexeme=yytext(); return Comentario;}

/*VARIABLE TIPO BIT*/
(0|1|NULL) {lexeme=yytext(); return Bit;}

/*VARIABLE TIPO INT*/
({Numero}) {lexeme=yytext(); return Int;}
("(-"{D}+")")|{D}+ {lexeme=yytext(); return Int;}

/*VARIABLE TIPO STRING*/
("'"(.[^'])*"'") {lexeme=yytext(); return String;}

/*VARIABLE TIPO FLOAT*/
({Numero}+"."{Numero}*) {lexeme=yytext(); return Float;}
//({Numero}+.({Numero}*)((E|e)(+|-)({Numero}))?) {lexeme=yytext(); return Float;}

/*SIMBOLO IGUAL*/
"=" {return Simbolo Igual;}
/*SUMA*/
("+") {return Suma;}
/*RESTA*/
"-" {return Resta;}
/*MULTIPLICACION*/
"*" {return Multiplicacion;}
/*DIVISION*/
"/" {return Division;}
/*IDENTIFICADOR*/
{L}({L}|{D}|{Guion})* {lexeme=yytext(); return Identificador;}
 . {return ERROR;}

/* Finaliza Sección de Reglas */
